---
- hosts: stream-go
  remote_user: trust

  tasks: 
      - name: Check that the somefile.conf exists 
        stat: 
          path: /home/trust/file.txt
        register: stat_result 
      - name: Create the file if it doesnt exist already 
        file: 
          path: /home/trust/file.txt
          state: directory 
        when: stat_result.stat.exists == False 
