---
- hosts: stream-iota
  remote_user: root 

  tasks:
    - name: create directory
      file: 
        path={{item}}
        state=directory 
      with_items: 
        - /data/iri/
        - /data/iri/data
        - /data/iri/conf
    - name: copy neighbors
      copy: src=/home/ubuntu/ans_d/neighbors dest=/data/iri/conf/neighbors
    - name: pull image from harbor
      shell: sudo docker pull 10.240.4.1/streamnet-dag/{{ image_name }}:{{ image_tag }}
    - name: clear docker
      shell: sudo docker rm -f stream_iota
    - name: delete data
      shell: sudo rm -rf /data/iri/data/*
    - name: start docker
      shell: sudo docker run -d -p 14700:14700 -p 13700:13700 --name stream_iota -v /data/iri/data:/iri/data/ -v /data/iri/conf/neighbors:/iri/conf/neighbors 10.240.4.1/streamnet-dag/{{ image_name }}:{{ image_tag }} /entrypoint.sh
